/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

module iiitb_usr(clk, reset, ctrl, d, q);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  input clk;
  input [1:0] ctrl;
  input [3:0] d;
  output [3:0] q;
  wire [3:0] r_next;
  input reset;
  sky130_fd_sc_hd__nand2_1 _20_ (
    .A(ctrl[0]),
    .B(ctrl[1]),
    .Y(_00_)
  );
  sky130_fd_sc_hd__nor2_1 _21_ (
    .A(d[0]),
    .B(_00_),
    .Y(_01_)
  );
  sky130_fd_sc_hd__nand3b_1 _22_ (
    .A_N(ctrl[0]),
    .B(ctrl[1]),
    .C(q[3]),
    .Y(_02_)
  );
  sky130_fd_sc_hd__clkinv_1 _23_ (
    .A(ctrl[0]),
    .Y(_03_)
  );
  sky130_fd_sc_hd__clkinv_1 _24_ (
    .A(ctrl[1]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__nand3_1 _25_ (
    .A(_03_),
    .B(_04_),
    .C(q[0]),
    .Y(_05_)
  );
  sky130_fd_sc_hd__o21ai_0 _26_ (
    .A1(ctrl[1]),
    .A2(q[1]),
    .B1(ctrl[0]),
    .Y(_06_)
  );
  sky130_fd_sc_hd__a31oi_1 _27_ (
    .A1(_05_),
    .A2(_02_),
    .A3(_06_),
    .B1(_01_),
    .Y(r_next[0])
  );
  sky130_fd_sc_hd__nand3b_1 _28_ (
    .A_N(ctrl[1]),
    .B(ctrl[0]),
    .C(q[2]),
    .Y(_07_)
  );
  sky130_fd_sc_hd__nand3_1 _29_ (
    .A(_03_),
    .B(_04_),
    .C(q[1]),
    .Y(_08_)
  );
  sky130_fd_sc_hd__o21ai_0 _30_ (
    .A1(ctrl[0]),
    .A2(q[0]),
    .B1(ctrl[1]),
    .Y(_09_)
  );
  sky130_fd_sc_hd__nor2_1 _31_ (
    .A(d[1]),
    .B(_00_),
    .Y(_10_)
  );
  sky130_fd_sc_hd__a31oi_1 _32_ (
    .A1(_08_),
    .A2(_07_),
    .A3(_09_),
    .B1(_10_),
    .Y(r_next[1])
  );
  sky130_fd_sc_hd__nor2_1 _33_ (
    .A(d[2]),
    .B(_00_),
    .Y(_11_)
  );
  sky130_fd_sc_hd__nand3_1 _34_ (
    .A(_03_),
    .B(_04_),
    .C(q[2]),
    .Y(_12_)
  );
  sky130_fd_sc_hd__o21ai_0 _35_ (
    .A1(ctrl[1]),
    .A2(q[3]),
    .B1(ctrl[0]),
    .Y(_14_)
  );
  sky130_fd_sc_hd__nand2_1 _36_ (
    .A(ctrl[1]),
    .B(q[1]),
    .Y(_15_)
  );
  sky130_fd_sc_hd__a31oi_1 _37_ (
    .A1(_12_),
    .A2(_14_),
    .A3(_15_),
    .B1(_11_),
    .Y(r_next[2])
  );
  sky130_fd_sc_hd__nand3b_1 _38_ (
    .A_N(ctrl[1]),
    .B(ctrl[0]),
    .C(q[0]),
    .Y(_16_)
  );
  sky130_fd_sc_hd__nand3_1 _39_ (
    .A(_03_),
    .B(_04_),
    .C(q[3]),
    .Y(_17_)
  );
  sky130_fd_sc_hd__o21ai_0 _40_ (
    .A1(ctrl[0]),
    .A2(q[2]),
    .B1(ctrl[1]),
    .Y(_18_)
  );
  sky130_fd_sc_hd__nor2_1 _41_ (
    .A(d[3]),
    .B(_00_),
    .Y(_19_)
  );
  sky130_fd_sc_hd__a31oi_1 _42_ (
    .A1(_17_),
    .A2(_16_),
    .A3(_18_),
    .B1(_19_),
    .Y(r_next[3])
  );
  sky130_fd_sc_hd__clkinv_1 _43_ (
    .A(reset),
    .Y(_13_)
  );
  sky130_fd_sc_hd__dfrtp_1 _44_ (
    .CLK(clk),
    .D(r_next[0]),
    .Q(q[0]),
    .RESET_B(_13_)
  );
  sky130_fd_sc_hd__dfrtp_1 _45_ (
    .CLK(clk),
    .D(r_next[1]),
    .Q(q[1]),
    .RESET_B(_13_)
  );
  sky130_fd_sc_hd__dfrtp_1 _46_ (
    .CLK(clk),
    .D(r_next[2]),
    .Q(q[2]),
    .RESET_B(_13_)
  );
  sky130_fd_sc_hd__dfrtp_1 _47_ (
    .CLK(clk),
    .D(r_next[3]),
    .Q(q[3]),
    .RESET_B(_13_)
  );
endmodule
