/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* top =  1  *)
(* src = "iiitb_usr.v:1" *)
module usr(clk, reset, ctrl, d, q);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  wire _46_;
  wire _47_;
  wire _48_;
  wire _49_;
  (* src = "iiitb_usr.v:2" *)
  input clk;
  (* src = "iiitb_usr.v:3" *)
  input [1:0] ctrl;
  (* src = "iiitb_usr.v:4" *)
  input [3:0] d;
  (* src = "iiitb_usr.v:5" *)
  output [3:0] q;
  (* src = "iiitb_usr.v:8" *)
  wire [3:0] r_next;
  (* src = "iiitb_usr.v:8" *)
  reg [3:0] r_reg;
  (* src = "iiitb_usr.v:2" *)
  input reset;
  sky130_fd_sc_hd__nand2_1 _50_ (
    .A(_17_),
    .B(_18_),
    .Y(_22_)
  );
  sky130_fd_sc_hd__nor2_1 _51_ (
    .A(_20_),
    .B(_22_),
    .Y(_24_)
  );
  sky130_fd_sc_hd__nand3b_1 _52_ (
    .A_N(_17_),
    .B(_18_),
    .C(_19_),
    .Y(_25_)
  );
  sky130_fd_sc_hd__clkinv_1 _53_ (
    .A(_17_),
    .Y(_26_)
  );
  sky130_fd_sc_hd__clkinv_1 _54_ (
    .A(_18_),
    .Y(_28_)
  );
  sky130_fd_sc_hd__nand3_1 _55_ (
    .A(_26_),
    .B(_28_),
    .C(_41_),
    .Y(_30_)
  );
  sky130_fd_sc_hd__o21ai_0 _56_ (
    .A1(_18_),
    .A2(_49_),
    .B1(_17_),
    .Y(_31_)
  );
  sky130_fd_sc_hd__a31oi_1 _57_ (
    .A1(_30_),
    .A2(_25_),
    .A3(_31_),
    .B1(_24_),
    .Y(_21_)
  );
  sky130_fd_sc_hd__nand3b_1 _58_ (
    .A_N(_18_),
    .B(_17_),
    .C(_23_),
    .Y(_32_)
  );
  sky130_fd_sc_hd__nand3_1 _59_ (
    .A(_26_),
    .B(_28_),
    .C(_49_),
    .Y(_34_)
  );
  sky130_fd_sc_hd__o21ai_0 _60_ (
    .A1(_17_),
    .A2(_41_),
    .B1(_18_),
    .Y(_36_)
  );
  sky130_fd_sc_hd__nor2_1 _61_ (
    .A(_27_),
    .B(_22_),
    .Y(_37_)
  );
  sky130_fd_sc_hd__a31oi_1 _62_ (
    .A1(_34_),
    .A2(_32_),
    .A3(_36_),
    .B1(_37_),
    .Y(_29_)
  );
  sky130_fd_sc_hd__nor2_1 _63_ (
    .A(_33_),
    .B(_22_),
    .Y(_38_)
  );
  sky130_fd_sc_hd__nand3_1 _64_ (
    .A(_26_),
    .B(_28_),
    .C(_23_),
    .Y(_40_)
  );
  sky130_fd_sc_hd__nand2_1 _65_ (
    .A(_18_),
    .B(_49_),
    .Y(_43_)
  );
  sky130_fd_sc_hd__o21ai_0 _66_ (
    .A1(_18_),
    .A2(_19_),
    .B1(_17_),
    .Y(_44_)
  );
  sky130_fd_sc_hd__a31oi_1 _67_ (
    .A1(_40_),
    .A2(_43_),
    .A3(_44_),
    .B1(_38_),
    .Y(_35_)
  );
  sky130_fd_sc_hd__nand3b_1 _68_ (
    .A_N(_18_),
    .B(_17_),
    .C(_41_),
    .Y(_45_)
  );
  sky130_fd_sc_hd__nand3_1 _69_ (
    .A(_26_),
    .B(_28_),
    .C(_19_),
    .Y(_46_)
  );
  sky130_fd_sc_hd__o21ai_0 _70_ (
    .A1(_17_),
    .A2(_23_),
    .B1(_18_),
    .Y(_47_)
  );
  sky130_fd_sc_hd__nor2_1 _71_ (
    .A(_39_),
    .B(_22_),
    .Y(_48_)
  );
  sky130_fd_sc_hd__a31oi_1 _72_ (
    .A1(_46_),
    .A2(_45_),
    .A3(_47_),
    .B1(_48_),
    .Y(_42_)
  );
  (* src = "iiitb_usr.v:9" *)
  always @(posedge clk or posedge reset)
    if (reset)
      r_reg[0] <= 0;
    else
      r_reg[0] <= r_next[0];
  (* src = "iiitb_usr.v:9" *)
  always @(posedge clk or posedge reset)
    if (reset)
      r_reg[1] <= 0;
    else
      r_reg[1] <= r_next[1];
  (* src = "iiitb_usr.v:9" *)
  always @(posedge clk or posedge reset)
    if (reset)
      r_reg[2] <= 0;
    else
      r_reg[2] <= r_next[2];
  (* src = "iiitb_usr.v:9" *)
  always @(posedge clk or posedge reset)
    if (reset)
      r_reg[3] <= 0;
    else
      r_reg[3] <= r_next[3];
  assign q = r_reg;
  assign _17_ = ctrl[0];
  assign _18_ = ctrl[1];
  assign _41_ = r_reg[0];
  assign _49_ = r_reg[1];
  assign _19_ = r_reg[3];
  assign _20_ = d[0];
  assign r_next[0] = _21_;
  assign _23_ = r_reg[2];
  assign _27_ = d[1];
  assign r_next[1] = _29_;
  assign _33_ = d[2];
  assign r_next[2] = _35_;
  assign _39_ = d[3];
  assign r_next[3] = _42_;
endmodule
